<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Coink.Api</AssemblyName>
    <RootNamespace>Coink.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Coink.Application/Coink.Application.csproj" />
    <ProjectReference Include="../Coink.Infrastructure/Coink.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
